<?php

namespace Database\Seeders\Main;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                "title" => "İnce Memed",
                "slug" => "ince-memed",
                "category_id" => 1,
                "author" => "Yaşar Kemal",
                "description" => "Yaşar Kemal'in en ünlü eseri. Çukurova'da geçen destansı bir hikaye.",
                "meta_title" => "İnce Memed - Yaşar Kemal | Kitap Satın Al",
                "meta_description" => "Yaşar Kemal'in İnce Memed kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 259.90,
                "list_price_cents" => 25990,
                "stock_quantity" => 10,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["ince-memed.png"]
            ],
            [
                "title" => "Tutunamayanlar",
                "slug" => "tutunamayanlar",
                "category_id" => 1,
                "author" => "Oğuz Atay",
                "description" => "Türk edebiyatının en önemli eserlerinden biri. Modern Türk romanının başyapıtı.",
                "meta_title" => "Tutunamayanlar - Oğuz Atay | Kitap Satın Al",
                "meta_description" => "Oğuz Atay'ın Tutunamayanlar kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 339.50,
                "list_price_cents" => 33950,
                "stock_quantity" => 20,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["tutunamayanlar.png"]
            ],
            [
                "title" => "Kürk Mantolu Madonna",
                "slug" => "kurk-mantolu-madonna",
                "category_id" => 1,
                "author" => "Sabahattin Ali",
                "description" => "Sabahattin Ali'nin en çok okunan romanı. Aşk ve yalnızlık üzerine derin bir hikaye.",
                "meta_title" => "Kürk Mantolu Madonna - Sabahattin Ali | Kitap Satın Al",
                "meta_description" => "Sabahattin Ali'nin Kürk Mantolu Madonna kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 169.90,
                "list_price_cents" => 16990,
                "stock_quantity" => 4,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["kurk-mantolu-madonna.png"]
            ],
            [
                "title" => "Fareler ve İnsanlar",
                "slug" => "fareler-ve-insanlar",
                "category_id" => 1,
                "author" => "John Steinbeck",
                "description" => "John Steinbeck'in en ünlü eseri. Dostluk ve hayaller üzerine dokunaklı bir hikaye.",
                "meta_title" => "Fareler ve İnsanlar - John Steinbeck | Kitap Satın Al",
                "meta_description" => "John Steinbeck'in Fareler ve İnsanlar kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 175.50,
                "list_price_cents" => 17550,
                "stock_quantity" => 8,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["fareler-ve-insanlar.png"]
            ],
            [
                "title" => "Şeker Portakalı",
                "slug" => "seker-portakali",
                "category_id" => 1,
                "author" => "Jose Mauro De Vasconcelos",
                "description" => "Brezilyalı yazarın en ünlü eseri. Çocukluk ve hayal gücü üzerine duygusal bir hikaye.",
                "meta_title" => "Şeker Portakalı - Jose Mauro De Vasconcelos | Kitap Satın Al",
                "meta_description" => "Jose Mauro De Vasconcelos'un Şeker Portakalı kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 149.90,
                "list_price_cents" => 14990,
                "stock_quantity" => 1,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["seker-portakali.png"]
            ],
            [
                "title" => "Sen Yola Çık Yol Sana Görünür",
                "slug" => "sen-yola-cik-yol-sana-gorunur",
                "category_id" => 2,
                "author" => "Hakan Mengüç",
                "description" => "Hakan Mengüç'ün kişisel gelişim kitabı. Hayat yolculuğu ve motivasyon üzerine.",
                "meta_title" => "Sen Yola Çık Yol Sana Görünür - Hakan Mengüç | Kitap Satın Al",
                "meta_description" => "Hakan Mengüç'ün Sen Yola Çık Yol Sana Görünür kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 184.50,
                "list_price_cents" => 18450,
                "stock_quantity" => 7,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["sen-yola-cik-yol-sana-gorunur.png"]
            ],
            [
                "title" => "Kara Delikler",
                "slug" => "kara-delikler",
                "category_id" => 3,
                "author" => "Stephen Hawking",
                "description" => "Stephen Hawking'in kara delikler hakkındaki bilimsel açıklamaları. Evrenin sırları.",
                "meta_title" => "Kara Delikler - Stephen Hawking | Kitap Satın Al",
                "meta_description" => "Stephen Hawking'in Kara Delikler kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 219.90,
                "list_price_cents" => 21990,
                "stock_quantity" => 2,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["kara-delikler.png"]
            ],
            [
                "title" => "Allah De Ötesini Bırak",
                "slug" => "allah-de-otesini-birak",
                "category_id" => 4,
                "author" => "Uğur Koşar",
                "description" => "Uğur Koşar'ın dini ve manevi konulardaki düşünceleri. İslami perspektiften hayat.",
                "meta_title" => "Allah De Ötesini Bırak - Uğur Koşar | Kitap Satın Al",
                "meta_description" => "Uğur Koşar'ın Allah De Ötesini Bırak kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 157.50,
                "list_price_cents" => 15750,
                "stock_quantity" => 18,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["allah-de-otesini-birak.png"]
            ],
            [
                "title" => "Aşk 5 Vakittir",
                "slug" => "ask-5-vakittir",
                "category_id" => 4,
                "author" => "Mehmet Yıldız",
                "description" => "Mehmet Yıldız'ın aşk ve ilişkiler üzerine yazdığı kitap. Modern aşk anlayışı.",
                "meta_title" => "Aşk 5 Vakittir - Mehmet Yıldız | Kitap Satın Al",
                "meta_description" => "Mehmet Yıldız'ın Aşk 5 Vakittir kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 159.50,
                "list_price_cents" => 15950,
                "stock_quantity" => 9,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["ask-5-vakittir.png"]
            ],
            [
                "title" => "Benim Zürafam Uçabilir",
                "slug" => "benim-zurafam-ucabilir",
                "category_id" => 7,
                "author" => "Mert Arık",
                "description" => "Mert Arık'ın çocuklar için yazdığı eğlenceli hikaye. Hayal gücü ve yaratıcılık.",
                "meta_title" => "Benim Zürafam Uçabilir - Mert Arık | Kitap Satın Al",
                "meta_description" => "Mert Arık'ın Benim Zürafam Uçabilir kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 129.90,
                "list_price_cents" => 12990,
                "stock_quantity" => 12,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["benim-zurafam-ucabilir.png"]
            ],
            [
                "title" => "Kuyucaklı Yusuf",
                "slug" => "kuyucakli-yusuf",
                "category_id" => 1,
                "author" => "Sabahattin Ali",
                "description" => "Sabahattin Ali'nin en ünlü romanlarından biri. Anadolu'da geçen hikaye.",
                "meta_title" => "Kuyucaklı Yusuf - Sabahattin Ali | Kitap Satın Al",
                "meta_description" => "Sabahattin Ali'nin Kuyucaklı Yusuf kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 179.90,
                "list_price_cents" => 17990,
                "stock_quantity" => 2,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["kuyucakli-yusuf.png"]
            ],
            [
                "title" => "Kamyon - Seçme Öyküler",
                "slug" => "kamyon-secme-oykuler",
                "category_id" => 5,
                "author" => "Sabahattin Ali",
                "description" => "Sabahattin Ali'nin en güzel öykülerinin derlendiği kitap. Türk öykücülüğünün başyapıtları.",
                "meta_title" => "Kamyon - Seçme Öyküler - Sabahattin Ali | Kitap Satın Al",
                "meta_description" => "Sabahattin Ali'nin Kamyon - Seçme Öyküler kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 169.50,
                "list_price_cents" => 16950,
                "stock_quantity" => 9,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["kamyon-secme-oykuler.png"]
            ],
            [
                "title" => "Kendime Düşünceler",
                "slug" => "kendime-dusunceler",
                "category_id" => 6,
                "author" => "Marcus Aurelius",
                "description" => "Roma İmparatoru Marcus Aurelius'un kişisel günlüğü. Stoik felsefe ve yaşam bilgeliği.",
                "meta_title" => "Kendime Düşünceler - Marcus Aurelius | Kitap Satın Al",
                "meta_description" => "Marcus Aurelius'un Kendime Düşünceler kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 214.90,
                "list_price_cents" => 21490,
                "stock_quantity" => 1,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["kendime-dusunceler.png"]
            ],
            [
                "title" => "Denemeler - Hasan Ali Yücel Klasikleri",
                "slug" => "denemeler-montaigne",
                "category_id" => 6,
                "author" => "Michel de Montaigne",
                "description" => "Montaigne'in en ünlü eseri. İnsan doğası ve yaşam üzerine derin düşünceler.",
                "meta_title" => "Denemeler - Michel de Montaigne | Kitap Satın Al",
                "meta_description" => "Michel de Montaigne'in Denemeler kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 229.90,
                "list_price_cents" => 22990,
                "stock_quantity" => 4,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["denemeler-montaigne.png"]
            ],
            [
                "title" => "Animal Farm",
                "slug" => "animal-farm",
                "category_id" => 1,
                "author" => "George Orwell",
                "description" => "George Orwell'in en ünlü eserlerinden biri. Politik alegori ve toplumsal eleştiri.",
                "meta_title" => "Animal Farm - George Orwell | Kitap Satın Al",
                "meta_description" => "George Orwell'in Animal Farm kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 189.90,
                "list_price_cents" => 18990,
                "stock_quantity" => 1,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["animal-farm.png"]
            ],
            [
                "title" => "Dokuzuncu Hariciye Koğuşu",
                "slug" => "dokuzuncu-hariciye-kogusu",
                "category_id" => 1,
                "author" => "Peyami Safa",
                "description" => "Peyami Safa'nın en ünlü romanı. Hastalık ve umut üzerine dokunaklı bir hikaye.",
                "meta_title" => "Dokuzuncu Hariciye Koğuşu - Peyami Safa | Kitap Satın Al",
                "meta_description" => "Peyami Safa'nın Dokuzuncu Hariciye Koğuşu kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 174.50,
                "list_price_cents" => 17450,
                "stock_quantity" => 0,
                "store_id" => 1,
                "store_name" => "i&d",
                "sold_quantity" => 0,
                "images" => ["dokuzuncu-hariciye-kogusu.png"]
            ],
            // Ahmet Kitapçı'nın ürünleri (store_id: 2)
            [
                "title" => "Suç ve Ceza",
                "slug" => "suc-ve-ceza",
                "category_id" => 1,
                "author" => "Dostoyevski",
                "description" => "Dostoyevski'nin en ünlü eseri. Suç, ceza ve vicdan üzerine derin bir psikolojik roman.",
                "meta_title" => "Suç ve Ceza - Dostoyevski | Kitap Satın Al",
                "meta_description" => "Dostoyevski'nin Suç ve Ceza kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 246.50,
                "list_price_cents" => 24650,
                "stock_quantity" => 25,
                "store_id" => 2,
                "store_name" => "Ahmet'in Kitap Dünyası",
                "sold_quantity" => 0,
                "images" => ["suc-ve-ceza.png"]
            ],
            [
                "title" => "Beyaz Geceler",
                "slug" => "beyaz-geceler",
                "category_id" => 1,
                "author" => "Dostoyevski",
                "description" => "Dostoyevski'nin kısa ama etkileyici romanı. Aşk ve yalnızlık üzerine duygusal bir hikaye.",
                "meta_title" => "Beyaz Geceler - Dostoyevski | Kitap Satın Al",
                "meta_description" => "Dostoyevski'nin Beyaz Geceler kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 129.50,
                "list_price_cents" => 12950,
                "stock_quantity" => 15,
                "store_id" => 2,
                "store_name" => "Ahmet'in Kitap Dünyası",
                "sold_quantity" => 0,
                "images" => ["beyaz-geceler.png"]
            ],
            [
                "title" => "Karamazov Kardeşler",
                "slug" => "karamazov-kardesler",
                "category_id" => 1,
                "author" => "Dostoyevski",
                "description" => "Dostoyevski'nin son ve en büyük eseri. Aile, din ve ahlak üzerine derin bir roman.",
                "meta_title" => "Karamazov Kardeşler - Dostoyevski | Kitap Satın Al",
                "meta_description" => "Dostoyevski'nin Karamazov Kardeşler kitabını uygun fiyatlarla satın alın. Hızlı kargo, güvenli ödeme.",
                "list_price" => 294.50,
                "list_price_cents" => 29450,
                "stock_quantity" => 8,
                "store_id" => 2,
                "store_name" => "Ahmet'in Kitap Dünyası",
                "sold_quantity" => 0,
                "images" => ["karamazov-kardesler.png"]
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}